DROP TABLE IF EXISTS player;
DROP TABLE IF EXISTS team;

CREATE TABLE team (
                      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                      name VARCHAR(255) NOT NULL,
                      acronym VARCHAR(50) NOT NULL,
                      budget DECIMAL(19,2) NOT NULL
);

CREATE TABLE player (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        position VARCHAR(50) NOT NULL,
                        team_id BIGINT,
                        CONSTRAINT fk_team FOREIGN KEY (team_id) REFERENCES team(id)
);
